### 카카오 로그인 버튼 클릭
GET http://15.165.231.19:8080/api/login/kakao
Content-Type: application/json

### 카카오 코드로 살랑이 서버로부터 액세스 토큰 발급
GET http://15.165.231.19:8080/api/login/kakao/token?code=aH2sHl41OKXXCtyIRyU0CfDW3dgwl-16jTilcTDAvZJBGynZ9VXfLaBbgqQKKcleAAABi4oG62no6jj-qNQmaA
Content-Type: application/json

### 구글 로그인 버튼 클릭
GET http://localhost:8080/api/login/google
Content-Type: application/json

### 로컬 로그인 버튼 클릭
GET http://localhost:8080/api/login/kakao
Content-Type: application/json

### 로컬에서 액세스 토큰 발급
GET http://localhost:8080/api/login/kakao/token?code=iBKjkBdHJDU3a57ZiPM_344lHvMTjmgtUwqFdVrx5TSE1llY1hEj6tIKJxoKPXSYAAABi4oZjRr7Ewsnpgvovw
Content-Type: application/json

### 아이디, 패스워드로 회원가입
POST http://localhost:8080/api/join
Content-Type: application/json

{
  "loginID": "gitchan",
  "loginPassword": "gitchan1234"
}

### 아이디, 패스워드로 로그인
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "loginID": "gitchan",
  "loginPassword": "gitchan1234"
}
